accumulate_grad_batches: 16
dataloader:
  common:
    batch_size: 256
    num_workers: 6
dataset:
  common:
    feature_scaling: false
    filter_args:
      N: 3
      Wn: !!python/tuple
      - 0.5
      - 60
      btype: bandpass
    filter_type: butter
    include_filtered_signal: false
    include_labels: {}
    include_original_signal: false
    mean_normalization: true
    predicate: null
    signal_dtype: float32
  eval:
    hdf5_filename: ptb-xl/validation.hdf5
  train:
    hdf5_filename: ptb-xl/train.hdf5
in_leads:
- 0
- 1
- 8
lr_scheduler:
  args:
    factor: 0.5975501221062813
    patience: 3
  type: ReduceLROnPlateau
max_epochs: 8
optimizer:
  args:
    betas:
    - 0.9106169979408167
    - 0.9612136205676224
    lr: 0.0029060970473349544
    weight_decay: 5.208804198628564e-06
  type: AdamW
out_leads:
- 6
- 7
- 9
- 10
- 11
reconstructor:
  args:
    base_channels: 16
    dilation_scale: 3
    kernel_size: 3
    num_layers: 3
  type: !!python/name:ecg.reconstructor.cnn.cnn.StackedCNN ''
