accumulate_grad_batches: 8
dataloader:
  common:
    batch_size: 128
    num_workers: 4
dataset:
  common:
    feature_scaling: false
    filter_args:
      N: 3
      Wn: !!python/tuple
      - 0.5
      - 60
      btype: bandpass
    filter_type: butter
    include_filtered_signal: false
    include_labels: {}
    include_original_signal: false
    mean_normalization: true
    predicate: null
    signal_dtype: float32
  eval:
    hdf5_filename: ptb-xl/validation.hdf5
  train:
    hdf5_filename: ptb-xl/train.hdf5
in_leads:
- 0
- 1
- 8
lr_scheduler:
  args:
    factor: 0.5986269041609817
    patience: 2
  type: ReduceLROnPlateau
max_epochs: 8
optimizer:
  args:
    betas:
    - 0.9091494051250636
    - 0.964802538848444
    lr: 0.0023091577420568253
    weight_decay: 0.0002987140973394854
  type: AdamW
out_leads:
- 6
- 7
- 9
- 10
- 11
reconstructor:
  args:
    bert_config_dict:
      enable_fp16: false
      hidden_act: gelu
      # hidden_dropout_prob: 0.2
      hidden_dropout_prob: 0.1
      hidden_size: 96
      initializer_range: 0.02
      intermediate_size: 96
      layer_norm_eps: 1.0e-12
      max_position_embeddings: 8192
      num_attention_heads: 4
      num_hidden_layers: 2
      pooler_type: weightpooler
      type_vocab_size: 2
      vocab_size: 100000
  type: !!python/name:ecg.reconstructor.transformer.fastformer.Fastformer ''
