name: ecg-reconstruction
channels:
  - intel
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - black
  - black-jupyter
  - h5py
  - intel-extension-for-pytorch==1.13.120
  - ipywidgets
  - ipykernel
  - jupyterlab
  - matplotlib
  - mkl
  - mkl-include
  - neurokit2
  - optuna
  - optuna-dashboard
  - pandas
  - pip
  - pip:
    - thop
    - torch-tb-profiler
  - pylint
  - pytorch=1.13.0
  - python=3.10
  - scikit-learn
  - scipy
  - tensorboard
  - tensorflow-cpu
  - tqdm
  - transformers
  - wfdb
