accumulate_grad_batches: 1
dataloader:
  common:
    batch_size: 128
    num_workers: 6
dataset:
  common:
    feature_scaling: false
    filter_args:
      N: 3
      Wn: !!python/tuple
      - 0.5
      - 60
      btype: bandpass
    filter_type: butter
    include_filtered_signal: false
    include_labels: {}
    include_original_signal: false
    mean_normalization: true
    predicate: null
    signal_dtype: float32
  eval:
    hdf5_filename: ptb-xl/validation.hdf5
  train:
    hdf5_filename: ptb-xl/train.hdf5
in_leads:
- 0
- 1
- 8
lr_scheduler:
  args:
    factor: 0.5
    patience: 5
  type: ReduceLROnPlateau
# max_epochs: 32
optimizer:
  args:
    lr: 0.01
    weight_decay: 0.05
  type: AdamW
out_leads:
- 6
- 7
- 9
- 10
- 11
reconstructor:
  args: {}
