accumulate_grad_batches: 8
dataloader:
  common:
    batch_size: 256
    num_workers: 6
dataset:
  common:
    feature_scaling: false
    filter_args:
      N: 3
      Wn: !!python/tuple
      - 0.5
      - 60
      btype: bandpass
    filter_type: butter
    include_filtered_signal: false
    include_labels: {}
    include_original_signal: false
    mean_normalization: true
    predicate: null
    signal_dtype: float32
  eval:
    hdf5_filename: ptb-xl/validation.hdf5
  train:
    hdf5_filename: ptb-xl/train.hdf5
in_leads:
- 0
- 1
- 8
lr_scheduler:
  args:
    factor: 0.5
    patience: 5
  type: ReduceLROnPlateau
max_epochs: 8
optimizer:
  args:
    betas:
    - 0.8768143971969894
    - 0.9637603487103914
    lr: 0.0007278094207865456
    weight_decay: 0.0037334853640910203
  type: AdamW
out_leads:
- 6
- 7
- 9
- 10
- 11
reconstructor:
  args:
    dilation_rate: 1
    # in_leads: 3
    kernel_size: 31
    min_channels: 28
    min_dilation: 3
    num_layers: 4
    # out_leads: 5
    bilinear: true
    out_conv_ext: true

  